version: "3.5"

services:
    api:
        build: ./api
        image: node:16.15.0
        working_dir: /api
        restart: always
        container_name: api
        ports:
            - "${API_PORT}:${API_PORT}"
        volumes:
            - ./api:/api
        expose:
            - "${API_PORT}"
        command: "yarn start:dev"
        env_file: .env

    php-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "alan.demit@hotmail.com"
            PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "${POSTGRES_PORT}:80"
